name: code_generator
description: code generation for flutter-maplibre-gl
publish_to: 'none'

version: 0.0.1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^1.2.1
  mustache_template: ^2.0.0
  recase: ^4.0.0

dev_dependencies:
  very_good_analysis: ^5.0.0