name: maplibre_gl_web
description: Web platform implementation of maplibre_gl
version: 0.18.0
repository: https://github.com/maplibre/flutter-maplibre-gl
issue_tracker: https://github.com/maplibre/flutter-maplibre-gl/issues

flutter:
  plugin:
    platforms:
      web:
        pluginClass: MapLibreMapPlugin
        fileName: maplibre_gl_web.dart

dependencies:
  js: ^0.6.7
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  meta: ^1.3.0
  maplibre_gl_platform_interface:
    git:
      url: https://github.com/maplibre/flutter-maplibre-gl.git
      path: maplibre_gl_platform_interface
      ref: main
  image: ^4.0.17
  web: ^0.5.1

dependency_overrides:
  maplibre_gl_platform_interface:
    path: ../maplibre_gl_platform_interface

dev_dependencies:
  flutter_lints: ^4.0.0

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=3.22.0 <4.0.0"