name: maplibre_gl_mobile
description: "A new Flutter plugin project."
version: 0.0.1
homepage: https://github.com/maplibre/flutter-maplibre-gl

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  maplibre_gl_platform_interface:
    git:
      url: https://github.com/maplibre/flutter-maplibre-gl.git
      path: maplibre_gl_platform_interface
      ref: main

dev_dependencies: 
  plugin_platform_interface: ^2.1.8
  flutter_lints: ^3.0.2

flutter:
  plugin:
    implements: maplibre_gl
    platforms:
      android:
        package: org.maplibre.maplibregl
        pluginClass: MapLibreGlPlugin
        dartPluginClass: MapLibreAndroid
      ios:
        pluginClass: MapLibreGlPlugin
        dartPluginClass: MapLibreIos

