name: maplibre_gl_platform_interface
description: A common platform interface for the maplibre_gl plugin.
version: 0.18.0
repository: https://github.com/maplibre/flutter-maplibre-gl
issue_tracker: https://github.com/maplibre/flutter-maplibre-gl/issues

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=3.22.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.0.5

dev_dependencies:
  flutter_lints: ^4.0.0