name: maplibre_gl_platform_interface
description: A common platform interface for the maplibre_gl plugin.
version: 0.18.0
homepage: https://github.com/maplibre/flutter-maplibre-gl

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.0.5
  plugin_platform_interface: ^2.1.8

dev_dependencies: 
  flutter_lints: ^3.0.2

environment:
  sdk: '>=2.14.0 <3.0.0'
  flutter: '>=2.10.0'
